on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        env:
           deploy_url: ${{secrets.GITHUB_TOKEN}}
        run:
          curl $deploy_url
